version: "3"
services:
  build:
    image: titom73/mkdocs
    volumes:
      - ${PWD}:/docs
    command: ["build"]
    profiles:
      - build
  serve:
    image: titom73/mkdocs
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/docs
    profiles:
      - serve
  deploy:
    image: ${SCP_IMAGE:-kroniak/ssh-client}
    env_file:
      - .env
    user: "${KEYFILE_UID}"
    volumes:
      - ${PWD}:/docs:ro
      - ${KEYFILE_PATH}:/id_key:ro
      - /etc/passwd:/etc/passwd:ro
    command: scp -i /id_key -o StrictHostKeyChecking=no -r /docs/site/. ${DESTUSER}@${DESTSERVER}:${DESTDIR}
    profiles:
      - deploy
