---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyproblem-dep
spec:
  selector:
    matchLabels:
      app: xyproblem
  replicas: 1
  template:
    metadata:
      labels:
        app: xyproblem
    spec:
      initContainers:
      - name: pull-source
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          cd /source
          wget https://github.com/Alestrix/xyproblem.de/archive/refs/heads/master.zip
          unzip master.zip
          mv xyproblem.de-master/* .
          ls -al
        volumeMounts:
        - name: source
          mountPath: /source
      - name: build-site
        image: titom73/mkdocs:latest
        args:
        - build
        - -d
        - /site
        volumeMounts:
        - name: source
          mountPath: /docs
        - name: site
          mountPath: /site
      containers:
      - name: xyproblem-web
        image: joseluisq/static-web-server:2
        env:
        - name: SERVER_LOG_FORWARDED_FOR
          value: 'true'
        - name: SERVER_LOG_REMOTE_ADDRESS
          value: 'true'
        - name: SERVER_CORS_ALLOW_ORIGINS
          value: ""
        - name: SERVER_LOG_LEVEL
          value: info
        - name: SERVER_HEALTH
          value: 'true'
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
        volumeMounts:
        - name: site
          mountPath: /public
        resources:
          limits:
            cpu: "1000m"
            memory: "256M"
          requests:
            cpu: "10m"
            memory: "32M"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: source
        emptyDir:
          medium: Memory
      - name: site
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: xyproblem-svc
spec:
  selector:
    app: xyproblem
  ports:
    - protocol: TCP
      port: 80
